### ISSUE TITLE
awssum is deprecated

### ISSUE THREAD

**Issue by bufferoverflow** [mozilla/awsbox#142]
As mentioned on the awssum github page, awssum is deprected and aws-sdk shall be used.
Do you have any plans moving to aws-sdk?

**Comment by chilts** [comment]
I don't think we're currently looking at moving to aws-sdk at the moment, however since the AWS APIs are (pretty much always) backwards compatible, it means that awssum will continue to work as described.

I know that awsbox is still used in the Persona project, however for the Firefox Accounts project we're not using it. I'd be happy to help if you're interested in porting to the aws-sdk but I'm not sure how much value we'll get from it if we do. Does that seem reasonable?

**Comment by jrgm** [comment]
> however for the Firefox Accounts project we're not using it

Slightly off-topic, but there is test infrastructure for Fxa that is deployed as awsboxes. End off-topicness ;-)

**Comment by ckarlof** [comment]
@jrgm, eh? TeamCity?

**Comment by jrgm** [comment]
@ckarlof restmail, for one

**Comment by bufferoverflow** [comment]
Thanks @chilts , I recognized some missing regions(e.g. eu-central-1) within awssum and thought to create a PR for it, then I saw that its is depreceted.
